target-version = "py313"

line-length = 90
indent-width = 4

include = [
    "bumpi/**.py",
    "tests/**.py",
]

[lint.isort]
force-wrap-aliases = true
combine-as-imports = true
no-lines-before = ["local-folder"]

[lint]
preview = true

select = ["ALL"]
ignore = [
    # missing docstring
    "D",
    # type-checking block
    "TC001", "TC002", "TC003", "TC006",
    # replace random to secrets
    "S311",
    # `subprocess` module is possibly insecure
    "S404",
    # Missing copyright notice at top of file
    "CPY001",
    # Lambda may be unnecessary; consider inlining inner function
    "PLW0108",
    # `print` found
    "T201",
]

[lint.per-file-ignores]
"tests/**" = [
    # Use of `assert` detected
    "S101",
]

[lint.pylint]
# PLR0914
max-locals = 20
# PLR0911
max-returns = 10
# PLR0915
max-statements = 75